### ISSUE TITLE
java.net.URI doesn't handle URI without trailing "/"

### ISSUE THREAD

**Issue by ebremer** [afs/iri4ld#1]
java.net.URI uri = new java.net.URI("http://mysite.net");
        System.out.println(uri.resolve("picture.jpg")); 

returns "http://mysite.netpicture.jpg"

This creates an issue with:
https://github.com/jsonld-java/jsonld-java/blob/66012db2f53b009cedeae50c83b5594b9dd05e11/core/src/main/java/com/github/jsonldjava/utils/JsonLdUrl.java#L283

where the erroneous URI created with URI.resolve() yields "@ID" turning into blank nodes

@afs says:

Jena's own jena-iri gets it right.

   // NB The argument order can catch you out.
   IRI iri = IRIResolver.resolve("picture.jpg", "http://mysite.net" );
   System.out.println(iri);

but jsonld-java uses java.net.URI.

**Comment by afs** [comment]
iri4ld gets it right. iri4ld isn't java.util.URI nor does it use it.

See `TestResolve.resolve_18`.

Jena needs it's own IRI code because the JDK library code isn't accurate enough. But this isn't [Apache Jena jena-iri](https://github.com/apache/jena/tree/master/jena-iri), which is part of the Jena project. This is my personal project that _may_ replace jena-iri in the long term because it is lighter weight, easier to maintain and it is focused on LD needs of parsing, checking and resolving.
